FROM tiangolo/uvicorn-gunicorn-fastapi:python3.11-slim

WORKDIR /apps

COPY . /apps

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 80

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80"]
